version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: bash -c "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: bash -c "sleep 10 && 
              celery -A config worker -l INFO"
    depends_on:
      - redis
      - app


  celery_beat:
    build: .
    tty: true
    command: bash -c "sleep 20 && 
              celery -A config beat -l INFO -S django"
    depends_on:
      - redis
      - app