# Generated by Django 5.0.3 on 2024-03-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='time_done',
        ),
        migrations.AddField(
            model_name='habit',
            name='time_done_in_sec',
            field=models.PositiveIntegerField(default=120, verbose_name='time_done_in_sec'),
        ),
    ]
