# Generated by Django 5.0.3 on 2024-03-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habit_time_done_habit_time_done_in_sec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('once_a_day', 'once_a_day'), ('once_every_two_days', 'once_every_two_days'), ('once_every_three_days', 'once_every_three_days'), ('once_every_four_days', 'once_every_four_days'), ('once_every_five_days', 'once_every_five_days'), ('once_every_six_days', 'once_every_six_days'), ('once_a_week', 'once_a_week')], default='once_a_day', verbose_name='periodicity'),
        ),
    ]
