# Generated by Django 5.0.3 on 2024-03-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='is_published'),
        ),
    ]
