# Generated by Django 4.2.7 on 2024-03-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='time',
        ),
        migrations.AddField(
            model_name='habit',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start_date'),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(default='09:00:00', verbose_name='start_time'),
        ),
    ]
