# Generated by Django 4.2.7 on 2024-03-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_remove_habit_time_habit_start_date_habit_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[(1, 'once_a_day'), (2, 'once_every_two_days'), (3, 'once_every_three_days'), (4, 'once_every_four_days'), (5, 'once_every_five_days'), (6, 'once_every_six_days'), (7, 'once_a_week')], default='once_a_day', verbose_name='periodicity'),
        ),
    ]
