# Generated by Django 4.2.7 on 2024-03-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('once_a_day', 1), ('once_every_two_days', 2), ('once_every_three_days', 3), ('once_every_four_days', 4), ('once_every_five_days', 5), ('once_every_six_days', 6), ('once_a_week', 7)], default='once_a_day', verbose_name='periodicity'),
        ),
    ]
