# Generated by Django 4.2.7 on 2024-03-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_habit_periodicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='start_time',
        ),
        migrations.AddField(
            model_name='habit',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start_datetime'),
        ),
    ]
