# Generated by Django 4.2.7 on 2024-03-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_remove_habit_start_date_remove_habit_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='habit',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start_date'),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(default='09:00:00', verbose_name='start_time'),
        ),
    ]
